### ISSUE TITLE
Example of how to create text node

### ISSUE THREAD

**Issue by gnbl** [evtn/soda#1]
Please add an example of how to create a text node or setting the equivalent of innerHTML / textContent.

**Comment by gnbl** [comment]
Like this: `Tag("#text", "some text", x=0, y=5 )`

**Comment by evtn** [comment]
Added an explanation for text nodes [here](https://github.com/evtn/soda#text)

**Comment by evtn** [comment]
> Like this: `Tag("#text", "some text", x=0, y=5 )`

Your snippet would result in `<text x="0" y="5">some text</text>` (because '#' is stripped by [identifier function](https://github.com/evtn/soda/blob/f1ad69baa3f77b7219da35a3cafd2c93adf76d49/soda/tags.py#L37))

So basically it is equivalent to `Tag("text", "some text", x=0, y=5)` or `Tag.text("some text", x=0, y=5)`
